/**
 * Human-readable label for what generated a track.
 *
 * The database stores the internal pair (`provider` + `provider_model`), which
 * is not what anyone recognises. "poyo" + "V5_5" is a Suno 5.5 track — PoYo is
 * the API that fronts Suno in this app, not a generator in its own right — and
 * the model column holds internal identifiers like "V5_5" or
 * "minimax-music-2.6" rather than product names. Showing the raw columns would
 * be technically accurate and practically useless.
 *
 * Lives in lib/ rather than in the component because more than one surface
 * shows this, and a duplicated mapping is a duplicated thing to forget when a
 * provider is added.
 */

/** provider -> display name. Used on its own when no model is known. */
const PROVIDER_LABEL: Record<string, string> = {
  suno: "Suno",
  mureka: "Mureka",
  heartmula: "HeartMuLa",
  udio: "Udio",
  poyo: "Suno",
  tempolor: "Tempolor",
  apiframe: "APIFrame",
  apimart: "APIMart",
  musicgpt: "MusicGPT",
  lyria: "Lyria",
  minimax: "MiniMax",
  upload: "Uploaded",
};

/**
 * Model codes per provider. Keys are compared case-insensitively and with
 * separators removed, so "V5_5", "v5-5" and "v5.5" all resolve to the same
 * entry. These are the values /api/generate accepts (poyoValidModels) plus the
 * passthrough models the other providers use.
 *
 * A `*` key holds model codes whose label is complete on its own — the product
 * is named elsewhere, and prefixing the gateway would misattribute it
 * ("Suno MiniMax 2.6") or read as a stutter ("Lyria Lyria 3").
 */
const MODEL_LABEL: Record<string, Record<string, string>> = {
  poyo: {
    v4: "Suno 4",
    v45: "Suno 4.5",
    v4sall: "Suno 4.5 (S-All)",
    v4splus: "Suno 4.5 (S-Plus)",
    v5: "Suno 5",
    v55: "Suno 5.5",
    // MiniMax reached through the Suno endpoint, not generated by Suno. The
    // label stands alone so it cannot render as "Suno MiniMax 2.6".
    minimaxmusic26: "MiniMax 2.6",
  },
  mureka: {
    mureka1: "Mureka 1",
    mureka9: "Mureka 9",
  },
  minimax: {
    minimaxmusic2: "MiniMax 2",
    minimaxmusic26: "MiniMax 2.6",
  },
  lyria: {
    lyria2: "Lyria 2",
    lyria3: "Lyria 3",
  },
  apimart: {
    lyria2: "Lyria 2",
    lyria3: "Lyria 3",
    minimaxmusic2: "MiniMax 2",
    minimaxmusic26: "MiniMax 2.6",
    suno5: "Suno 5",
    suno55: "Suno 5.5",
  },
  apiframe: {
    lyria2: "Lyria 2",
    lyria3: "Lyria 3",
    minimaxmusic2: "MiniMax 2",
    minimaxmusic26: "MiniMax 2.6",
  },
  musicgpt: {
    musicgpt: "MusicGPT",
  },
  tempolor: {
    "1": "Tempolor v1",
    "2": "Tempolor v2",
    v1: "Tempolor v1",
    v2: "Tempolor v2",
  },
  heartmula: {
    heartmula: "HeartMuLa",
  },
};

/**
 * Providers that ARE the product they serve, so their prefix would only stutter
 * ("Lyria Lyria 3") or misattribute a passthrough ("Suno MiniMax 2.6"). The
 * model label is then used verbatim.
 */
const SELF_PROVIDERS = new Set([
  "poyo", "suno", "lyria", "mureka", "minimax", "musicgpt", "heartmula", "tempolor",
]);

/**
 * Gateway providers (APIMart, APIFrame) sell other people's models. For a model
 * that names a real product, the label stands alone — "APIMart Suno 5.5" would
 * make the track indistinguishable from a native one. For a model that does not
 * (a bare MiniMax build), the prefix is the only provenance left.
 */
const STANDALONE_MODEL: Record<string, Set<string>> = {
  "apimart/lyria3": new Set(["lyria3"]),
  "apimart/suno5": new Set(["suno5"]),
  "apimart/suno55": new Set(["suno55"]),
  "apimart/minimaxmusic26": new Set(["minimaxmusic26"]),
  "apiframe/lyria3": new Set(["lyria3"]),
  "apiframe/minimaxmusic26": new Set(["minimaxmusic26"]),
};

function normalizeModelKey(model: string): string {
  return model.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/**
 * Returns e.g. "Suno 5.5", "Lyria 3", "Mureka" (model unknown) or null when
 * neither column holds anything worth showing.
 *
 * Null rather than a placeholder: an uploaded track with no providerModel
 * still reports "Uploaded" from the provider alone, but a track where both are
 * empty shows nothing instead of an empty bullet. An unrecognised model falls
 * back to the raw string rather than being dropped — a wrong-but-present label
 * beats silently missing provenance.
 */
export function formatGenerator(
  provider: string | null | undefined,
  model?: string | null
): string | null {
  const providerKey = (provider ?? "").trim().toLowerCase();
  const rawModel = (model ?? "").trim();

  if (!providerKey && !rawModel) return null;

  const modelKey = normalizeModelKey(rawModel);
  const modelMap = MODEL_LABEL[providerKey];
  const modelLabel = modelKey && modelMap ? modelMap[modelKey] : undefined;

  // A model that is already a friendly name (older rows, or a provider we have
  // no entry for) is shown as-is rather than replaced by the provider name.
  if (!modelLabel && rawModel) {
    return /[a-z]/i.test(rawModel) && !modelKey ? rawModel : PROVIDER_LABEL[providerKey] ?? rawModel;
  }

  const providerLabel = PROVIDER_LABEL[providerKey];
  if (modelLabel && providerLabel) {
    const standAlone =
      SELF_PROVIDERS.has(providerKey) || STANDALONE_MODEL[`${providerKey}/${modelKey}`]?.has(modelKey);
    return standAlone ? modelLabel : `${providerLabel} ${modelLabel}`;
  }
  return modelLabel ?? providerLabel ?? rawModel ?? null;
}
