export type TrackDetailTrack = {
  id: string;
  title: string | null;
  provider: string;
  providerModel: string;
  jobId?: string | null;
  prompt: string;
  lyrics: string | null;
  lyricsTimestamps?: string | null;
  language?: string | null;
  translatedLyrics?: string | null;
  translatedLanguage?: string | null;
  status: "pending" | "generating" | "done" | "failed";
  audioUrl: string | null;
  audioUrlHd: string | null;
  format: string | null;
  formatHd: string | null;
  duration: number | null;
  completedAt?: string | null;
  createdAt: string;
  error: string | null;
  s3KeyHd: string | null;
  coverUrl?: string | null;
  s3KeyCover?: string | null;
  rating?: string | null;
  instrumental?: boolean | null;
  artistName?: string | null;
  composerName?: string | null;
  writerName?: string | null;
};
